package com.guatex.igconfiguraciones.formularios;

import com.guatex.igconfiguraciones.archivos.A_Params;
import com.guatex.igconfiguraciones.gestiones.G_ConsultasBD;
import com.guatex.igconfiguraciones.imagenes.RutasImagenes;
import com.guatex.igconfiguraciones.loggs.ArchivoLogs;
import com.guatex.igconfiguraciones.principal.GTXConfiguracionIG;
import com.guatex.igconfiguraciones.proceso.ImpresionesPendientes;
import com.guatex.igconfiguraciones.util.CifradoPassword;
import com.guatex.igconfiguraciones.util.Parametros;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author ESTEFANIECM
 */
public class P_Configuracion extends javax.swing.JPanel {

    ImageIcon icon = new ImageIcon(new RutasImagenes().getLoader());

    /**
     * Creates new form P_Configuracion
     */
    public P_Configuracion() {
        initComponents();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFechaActualizacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtTiempo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnMPver = new javax.swing.JButton();
        btnMUGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labelConexion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnMConexion = new javax.swing.JButton();
        btnMEconfig = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(510, 525));
        setMinimumSize(new java.awt.Dimension(510, 525));
        setPreferredSize(new java.awt.Dimension(510, 525));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 480));

        txtFechaActualizacion.setEditable(false);
        txtFechaActualizacion.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        txtFechaActualizacion.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setBackground(new java.awt.Color(238, 238, 238));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("minutos");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel2.setBackground(new java.awt.Color(238, 238, 238));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Última actualización: ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtPassword.setEditable(false);
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setBackground(new java.awt.Color(238, 238, 238));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Contraseña:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtTiempo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtTiempo.setForeground(new java.awt.Color(51, 51, 51));
        txtTiempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setBackground(new java.awt.Color(238, 238, 238));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Tiempo de espera: ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnMPver.setBackground(new java.awt.Color(255, 255, 255));
        btnMPver.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMPver.setForeground(new java.awt.Color(51, 51, 51));
        btnMPver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/ver.png"))); // NOI18N
        btnMPver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMPver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMPver.setDefaultCapable(false);
        btnMPver.setFocusPainted(false);
        btnMPver.setFocusable(false);
        btnMPver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMPver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPverActionPerformed(evt);
            }
        });

        btnMUGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnMUGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMUGuardar.setForeground(new java.awt.Color(102, 102, 102));
        btnMUGuardar.setText("Guardar");
        btnMUGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMUGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMUGuardar.setDefaultCapable(false);
        btnMUGuardar.setFocusPainted(false);
        btnMUGuardar.setFocusable(false);
        btnMUGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMUGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUGuardarActionPerformed(evt);
            }
        });

        labelConexion.setBackground(new java.awt.Color(238, 238, 238));
        labelConexion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelConexion.setForeground(new java.awt.Color(102, 102, 102));
        labelConexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/cargando.gif"))); // NOI18N
        labelConexion.setText("  Cargando...");
        labelConexion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelConexion.setIconTextGap(2);
        labelConexion.setMaximumSize(new java.awt.Dimension(280, 60));
        labelConexion.setMinimumSize(new java.awt.Dimension(280, 60));
        labelConexion.setPreferredSize(new java.awt.Dimension(280, 60));
        labelConexion.setRequestFocusEnabled(false);
        labelConexion.setVerifyInputWhenFocusTarget(false);

        jLabel4.setBackground(new java.awt.Color(238, 238, 238));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/ajustar.png"))); // NOI18N
        jLabel4.setText("Configuración de parámetros del sistema");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnMConexion.setBackground(new java.awt.Color(238, 238, 238));
        btnMConexion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMConexion.setForeground(new java.awt.Color(51, 51, 51));
        btnMConexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/conexion.png"))); // NOI18N
        btnMConexion.setText("   Probar conexión con Guatex");
        btnMConexion.setActionCommand("");
        btnMConexion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMConexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMConexion.setDefaultCapable(false);
        btnMConexion.setFocusPainted(false);
        btnMConexion.setFocusable(false);
        btnMConexion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMConexion.setMaximumSize(new java.awt.Dimension(280, 56));
        btnMConexion.setMinimumSize(new java.awt.Dimension(280, 56));
        btnMConexion.setPreferredSize(new java.awt.Dimension(280, 56));
        btnMConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMConexionActionPerformed(evt);
            }
        });

        btnMEconfig.setBackground(new java.awt.Color(238, 238, 238));
        btnMEconfig.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMEconfig.setForeground(new java.awt.Color(155, 65, 70));
        btnMEconfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/eliminar.png"))); // NOI18N
        btnMEconfig.setText("  Eliminar configuración");
        btnMEconfig.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMEconfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMEconfig.setDefaultCapable(false);
        btnMEconfig.setFocusPainted(false);
        btnMEconfig.setFocusable(false);
        btnMEconfig.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMEconfig.setMaximumSize(new java.awt.Dimension(280, 56));
        btnMEconfig.setMinimumSize(new java.awt.Dimension(280, 56));
        btnMEconfig.setPreferredSize(new java.awt.Dimension(280, 56));
        btnMEconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEconfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(txtFechaActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnMPver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(43, 43, 43)
                        .addComponent(btnMUGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMEconfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMPver))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMUGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(labelConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMEconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents
    /*Botón para guardar nuevos parámetros*/
    private void btnMUGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUGuardarActionPerformed
        Parametros p = new Parametros();
        try {
            int t = Integer.parseInt(this.txtTiempo.getText().trim());
            if (t >= 1) {
                p.setTiempoEspera(t);
                if (new A_Params().guardarParametrosArchivo()) {
                    GTXConfiguracionIG.parametros = new A_Params().cargarPropiedades();
                    int respuesta = JOptionPane.showConfirmDialog(null,
                            "El tiempo de espera para la impresión de guías pendientes \nse modificó correctamente.",
                            "Tiempo modificado", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if (respuesta == JOptionPane.OK_OPTION || respuesta == JOptionPane.CLOSED_OPTION) {
                        ArchivoLogs.getInstance().grabaLogFileAdministrador("------ Tiempo de espera modificado [" + t + "]", false);
                        mostrarParametros();
                        reinicioConsulta();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(jPanel1, "Por favor ingrese un número entero mayor o igual a 1", "Error - minutos de espera", JOptionPane.ERROR_MESSAGE);
                this.txtTiempo.setText("");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jPanel1, "Por favor ingrese un número entero mayor a 1", "Error - minutos de espera", JOptionPane.ERROR_MESSAGE);
            this.txtTiempo.setText("");
        }
    }//GEN-LAST:event_btnMUGuardarActionPerformed

    private void btnMPverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMPverActionPerformed

    private void btnMConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMConexionActionPerformed
        this.labelConexion.setVisible(true);
        new ConexionAPI().execute();
    }//GEN-LAST:event_btnMConexionActionPerformed

    private void btnMEconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEconfigActionPerformed
        eliminarConfiguracionAgente();
    }//GEN-LAST:event_btnMEconfigActionPerformed

    // Método que realiza la conexión al API en segundo plano
    private class ConexionAPI extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            String conexion = new G_ConsultasBD().pruebaConexion();
            labelConexion.setVisible(false);
            if (conexion.equals("OK")) {
                ArchivoLogs.getInstance().grabaLogFileAdministrador("------ Prueba de conexión con Guatex exitosa.", false);
                JOptionPane.showMessageDialog(jPanel1, "Sí hay conexión con Guatex.", "Conexión exitosa", JOptionPane.INFORMATION_MESSAGE);
            } else {
                ArchivoLogs.getInstance().grabaLogFileAdministrador("------ Prueba de conexión con Guatex fallida.", true);
                JOptionPane.showMessageDialog(jPanel1, "No hay conexión con Guatex.", "Error de conexión", JOptionPane.ERROR_MESSAGE);
            }
            return null;
        }
    }

    private void eliminarConfiguracionAgente() {
        String input = "";
        boolean ingresoValido = false;
        while (!ingresoValido) {
            input = JOptionPane.showInputDialog(this, "¿Está seguro que desea eliminar la configuración?\n\nEscriba 'aceptar' o 'cancelar':", "Eliminar configuración - Agente Guatex", JOptionPane.QUESTION_MESSAGE);
            if ("aceptar".equalsIgnoreCase(input) || "cancelar".equalsIgnoreCase(input)) {
                ingresoValido = true;
                if ("aceptar".equalsIgnoreCase(input)) {
                    eliminacion();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Por favor, escriba 'aceptar' o 'cancelar'.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public void eliminacion() {
        try {
            String carpetaArchivo = Parametros.getRutaRaiz() + "SERVICIO_IMPRESION_GUATEX";
            File carpeta = new File(carpetaArchivo);
            if (carpeta.exists()) {
                if (eliminarCarpeta(carpeta)) {
                    int enterado = JOptionPane.showConfirmDialog(this,
                            "Los archivos de configuración se eliminaron correctamente.\n\nPuedes proceder a configurar nuevamente el Agente Guatex.",
                            "¡Eliminación exitosa!",
                            JOptionPane.DEFAULT_OPTION,
                            JOptionPane.INFORMATION_MESSAGE);
                    if (enterado == JOptionPane.OK_OPTION) {
                        ArchivoLogs.getInstance().grabaLogFileAdministrador("------ Eliminación de configuración.", false);
                        GTXConfiguracionIG.reinicioConfiguracionIG();
                        GTXConfiguracionIG.inicioAgenteGuatex();
                        reinicioConsulta();
                        mostrarParametros();
                    }
                }
            } else {
                System.out.println("La carpeta no existe: " + carpetaArchivo);
            }
        } catch (Exception e) {
            System.out.println("error: ");
            ArchivoLogs.getInstance().grabaLogFileAdministrador("------ Excepción - Elimina configuración - " + e.getLocalizedMessage(), true);
            e.printStackTrace();
        }

    }

    private static void reinicioConsulta() {
        if (GTXConfiguracionIG.imp != null) {
            GTXConfiguracionIG.imp.detener();
        }
        GTXConfiguracionIG.imp = new ImpresionesPendientes();
        GTXConfiguracionIG.imp.iniciar();
    }

    private boolean eliminarCarpeta(File carpeta) {
        File[] archivos = carpeta.listFiles();
        if (archivos != null) { //Verifica que la carpeta contenga archivos
            for (File archivo : archivos) {
                if (archivo.isDirectory()) {
                    // Elimina subcarpetas
                    if (!eliminarCarpeta(archivo)) {
                        return false;
                    }
                } else {
                    // Elimina archivos
                    if (!archivo.delete()) {
                        System.out.println("No se pudo eliminar el archivo: " + archivo.getAbsolutePath());
                        return false;
                    }
                }
            }
        }
        // Elimina la carpeta al estar vacía
        if (carpeta.delete()) {
            return true;
        } else {
            return false;
        }
    }

    private void inicio() {
        this.labelConexion.setVisible(false);
        char defaultEchoChar = txtPassword.getEchoChar();
        this.btnMPver.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                txtPassword.setEchoChar((char) 0);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                txtPassword.setEchoChar(defaultEchoChar);
            }
        });
        mostrarParametros();
    }

    private void mostrarParametros() {
        this.txtTiempo.setText("");
        this.txtPassword.setText("");
        this.txtFechaActualizacion.setText("");
        try {
            int minutos = 0;
            try {
                minutos = Integer.valueOf(GTXConfiguracionIG.parametros.getProperty("minutosEspera"));
                if (minutos <= 0) {
                    minutos = new Parametros().getTiempoEspera();
                }
            } catch (NumberFormatException e) {
                minutos = new Parametros().getTiempoEspera();
            }
            String passwd = GTXConfiguracionIG.parametros.getProperty("password");
            if (passwd.isEmpty()) {
                passwd = new Parametros().getPassword();
            }
            String fecha = GTXConfiguracionIG.parametros.getProperty("fechaActualizacion");
            int mins = Integer.valueOf(minutos) / (60 * 1000);
            this.txtTiempo.setText("" + mins);
            this.txtPassword.setText(new CifradoPassword().decrypt(passwd));
            this.txtFechaActualizacion.setText(" " + fecha);

        } catch (Exception e) {
            ArchivoLogs.getInstance().grabaLogFileAdministrador("------ Excepción - Mostrar parámetros - " + e.getLocalizedMessage(), true);
            e.printStackTrace();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMConexion;
    private javax.swing.JButton btnMEconfig;
    private javax.swing.JButton btnMPver;
    private javax.swing.JButton btnMUGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelConexion;
    private javax.swing.JTextField txtFechaActualizacion;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
