package com.guatex.igconfiguraciones.formularios;

import com.guatex.igconfiguraciones.archivos.A_Impresoras;
import com.guatex.igconfiguraciones.entidades.E_Impresora;
import com.guatex.igconfiguraciones.entidades.E_Servicio;
import com.guatex.igconfiguraciones.loggs.ArchivoLogs;
import com.guatex.igconfiguraciones.principal.GTXConfiguracionIG;
import java.util.Collections;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESTEFANIECM
 */
public final class P_Impresoras extends javax.swing.JPanel {

    /**
     * Creates new form P_Impresoras
     */
    public P_Impresoras() {
        initComponents();
        iniciarPanel();
    }

    DefaultListModel modelo;
    DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
    A_Impresoras opciones = new A_Impresoras();

    private void iniciarPanel() {
        ((DefaultTableCellRenderer) this.tbImpresoras.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        this.tbImpresoras.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getColumn() == 2) {
                    validarSeleccionEliminar();
                }
            }
        });
        cargarTablaImpresoras();
    }

    private void cargarTablaImpresoras() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tbImpresoras.getModel();
        modeloTabla.setRowCount(0);
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        for (E_Impresora impresora : GTXConfiguracionIG.ListaImpresoras) {
            modeloTabla.addRow(new Object[]{impresora.getNombre(), impresora.getIp(), false, impresora.getIdImpresora()});
        }
        for (int i = 0; i < tbImpresoras.getColumnCount(); i++) {
            tbImpresoras.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        tbImpresoras.getColumnModel().getColumn(2).setCellRenderer(tbImpresoras.getDefaultRenderer(Boolean.class));
        tbImpresoras.getColumnModel().getColumn(2).setCellEditor(tbImpresoras.getDefaultEditor(Boolean.class));
        tbImpresoras.getColumnModel().getColumn(3).setMinWidth(0);
        tbImpresoras.getColumnModel().getColumn(3).setMaxWidth(0);
        tbImpresoras.getColumnModel().getColumn(3).setWidth(0);
    }

    private void validarSeleccionEliminar() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tbImpresoras.getModel();
        int filas = modeloTabla.getRowCount();
        int impresoraEliminar = 0;
        // Buscar casilla seleccionada seleccionadas
        for (int i = 0; i < filas; i++) {
            Boolean isSelected = (Boolean) modeloTabla.getValueAt(i, 2);
            if (isSelected != null && isSelected) {
                impresoraEliminar = i;
            }
        }
        String nombreImpresora = (String) modeloTabla.getValueAt(impresoraEliminar, 0);
        String idImpresora = (String) modeloTabla.getValueAt(impresoraEliminar, 3);

        if (!existeImpresoraEnServicios(idImpresora)) {
            int respuesta = JOptionPane.showConfirmDialog(null,
                    "¿Está seguro de eliminar la impresora '" + nombreImpresora + "'?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                GTXConfiguracionIG.ListaImpresoras.remove(impresoraEliminar);
                boolean actualizaArchivo = new A_Impresoras().guardarImpresorasArchivo();
                if (actualizaArchivo) {
                    ArchivoLogs.getInstance().grabaLogFileAdministrador("------ La impresora [" + nombreImpresora + "] fue eliminada.", false);
                    opciones.realizarBKarchivo();
                    cargarTablaImpresoras();
                }
            } else {
                cargarTablaImpresoras();
            }
        } else {
            int respuesta = JOptionPane.showConfirmDialog(null,
                    "No es posible eliminar la impresora '" + nombreImpresora + "' porque tiene servicios asociados. \nConsulte 'Mantenimiento de Servicios'.", "Alerta", JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if (respuesta == JOptionPane.OK_OPTION || respuesta == JOptionPane.CLOSED_OPTION) {
                cargarTablaImpresoras();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoConexion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtNombreImpresora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnMIGuardar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbImpresoras = new javax.swing.JTable();
        txtIPImpresora = new javax.swing.JTextField();

        setBackground(new java.awt.Color(238, 238, 238));
        setMinimumSize(new java.awt.Dimension(510, 525));
        setPreferredSize(new java.awt.Dimension(510, 525));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 498));

        jLabel1.setBackground(new java.awt.Color(238, 238, 238));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/addprinter.png"))); // NOI18N
        jLabel1.setText("Agregar impresora  ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel2.setBackground(new java.awt.Color(238, 238, 238));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombre de la impresora: ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtNombreImpresora.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(238, 238, 238));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Dirección IP:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnMIGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnMIGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMIGuardar.setForeground(new java.awt.Color(51, 51, 51));
        btnMIGuardar.setText("Guardar");
        btnMIGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMIGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMIGuardar.setDefaultCapable(false);
        btnMIGuardar.setFocusPainted(false);
        btnMIGuardar.setFocusable(false);
        btnMIGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMIGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMIGuardarActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(238, 238, 238));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Impresoras registradas:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tbImpresoras.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        tbImpresoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre impresora", "Dirección IP", "Eliminar impresora", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbImpresoras.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tbImpresoras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbImpresoras.setRowHeight(30);
        tbImpresoras.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbImpresoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbImpresorasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbImpresoras);
        if (tbImpresoras.getColumnModel().getColumnCount() > 0) {
            tbImpresoras.getColumnModel().getColumn(0).setResizable(false);
            tbImpresoras.getColumnModel().getColumn(1).setResizable(false);
            tbImpresoras.getColumnModel().getColumn(2).setResizable(false);
            tbImpresoras.getColumnModel().getColumn(3).setMinWidth(0);
            tbImpresoras.getColumnModel().getColumn(3).setPreferredWidth(0);
            tbImpresoras.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        txtIPImpresora.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(356, 356, 356)
                            .addComponent(btnMIGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtIPImpresora)
                                .addComponent(txtNombreImpresora))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIPImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnMIGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMIGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMIGuardarActionPerformed
        // TODO add your handling code here:
        String id = E_Impresora.generaIDimpresora();
        String nombre = txtNombreImpresora.getText().trim();
        String direccionIP = txtIPImpresora.getText().trim();
        if (!nombre.isEmpty() || !direccionIP.isEmpty()) {
                E_Impresora impresora = new E_Impresora();
                impresora.setIdImpresora(id);
                impresora.setNombre(nombre);
                impresora.setIp(direccionIP);
                boolean agregado = AgregaImpresora(impresora);
                if (agregado) {
                    boolean actualizaArchivo = opciones.guardarImpresorasArchivo();
                    if (actualizaArchivo) {
                        ArchivoLogs.getInstance().grabaLogFileAdministrador("------ La impresora [" + impresora.getNombre() + "] fue agregada.", false);
                        JOptionPane.showMessageDialog(this, "Impresora agregada exitosamente", "Impresoras", JOptionPane.INFORMATION_MESSAGE);
                        opciones.realizarBKarchivo();
                        limpiarCampos();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "La impresora con IP '" + direccionIP + "' ya existe.", "Impresoras", JOptionPane.ERROR_MESSAGE);
                }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre y la IP de la impresora.", "Alerta", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnMIGuardarActionPerformed

    private void tbImpresorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbImpresorasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbImpresorasMouseClicked

    private void limpiarCampos() {
        txtNombreImpresora.setText("");
        grupoConexion.clearSelection();
        cargarTablaImpresoras();
    }

    private boolean AgregaImpresora(E_Impresora nuevaImpresora) {
        for (E_Impresora i : GTXConfiguracionIG.ListaImpresoras) {
            if (i.getNombre().equals(nuevaImpresora.getIp())) {
                return false;
            }
        }
        GTXConfiguracionIG.ListaImpresoras.add(nuevaImpresora);
        return true;
    }

    private boolean existeImpresoraEnServicios(String idImpresora) {
        for (E_Servicio s : GTXConfiguracionIG.ListaServicios) {
            if (s.getIdImpresora().equals(idImpresora)) {
                return true;
            }
        }
        return false;
    }

    private boolean VentanaVisible() {
        return super.isVisible();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMIGuardar;
    private javax.swing.ButtonGroup grupoConexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbImpresoras;
    private javax.swing.JTextField txtIPImpresora;
    private javax.swing.JTextField txtNombreImpresora;
    // End of variables declaration//GEN-END:variables
}
