package com.guatex.igconfiguraciones.formularios;

import com.guatex.igconfiguraciones.archivos.A_Usuarios;
import com.guatex.igconfiguraciones.entidades.E_Servicio;
import com.guatex.igconfiguraciones.entidades.E_Usuario;
import com.guatex.igconfiguraciones.loggs.ArchivoLogs;
import com.guatex.igconfiguraciones.principal.GTXConfiguracionIG;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESTEFANIECM
 */
public final class P_Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form P_Usuarios
     */
    public P_Usuarios() {
        initComponents();
        iniciarPanel();
    }
    DefaultListModel modelo;
    DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
    A_Usuarios opciones = new A_Usuarios();

    private void iniciarPanel() {
        ((DefaultTableCellRenderer) this.tbUsuarios.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        this.tbUsuarios.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getColumn() == 2) {
                    validarSeleccionEliminar();
                }
            }
        });
        cargarTablaUsuarios();
    }

    private void cargarTablaUsuarios() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tbUsuarios.getModel();
        modeloTabla.setRowCount(0);
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        for (E_Usuario usuario : GTXConfiguracionIG.ListaUsuarios) {
            modeloTabla.addRow(new Object[]{usuario.getCodigoUsuario(), false, usuario.getIdRegistroUsuario()});
        }
        for (int i = 0; i < tbUsuarios.getColumnCount(); i++) {
            tbUsuarios.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        tbUsuarios.getColumnModel().getColumn(1).setCellRenderer(tbUsuarios.getDefaultRenderer(Boolean.class));
        tbUsuarios.getColumnModel().getColumn(1).setCellEditor(tbUsuarios.getDefaultEditor(Boolean.class));
        tbUsuarios.getColumnModel().getColumn(2).setMinWidth(0);
        tbUsuarios.getColumnModel().getColumn(2).setMaxWidth(0);
        tbUsuarios.getColumnModel().getColumn(2).setWidth(0);
    }

    private void validarSeleccionEliminar() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tbUsuarios.getModel();
        int filas = modeloTabla.getRowCount();
        int usuarioEliminar = 0;

        // Buscar casilla seleccionada seleccionadas
        for (int i = 0; i < filas; i++) {
            Boolean isSelected = (Boolean) modeloTabla.getValueAt(i, 2);
            if (isSelected != null && isSelected) {
                usuarioEliminar = i;
            }
        }
        String cPadre = (String) modeloTabla.getValueAt(usuarioEliminar, 0);
        String cUsuario = (String) modeloTabla.getValueAt(usuarioEliminar, 1);
        String idRegistro = (String) modeloTabla.getValueAt(usuarioEliminar, 3);

        if (!existeUsuarioEnServicios(idRegistro)) {
            int respuesta = JOptionPane.showConfirmDialog(null,
                    "¿Está seguro de eliminar el usuario '" + cPadre + "/" + cUsuario + "'?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                GTXConfiguracionIG.ListaUsuarios.remove(usuarioEliminar);
                boolean actualizaArchivo = new A_Usuarios().guardarUsuariosArchivo();
                if (actualizaArchivo) {
                    ArchivoLogs.getInstance().grabaLogFileAdministrador("------ El usuario [" + cUsuario + "] fue eliminado.", false);
                    opciones.realizarBKarchivo();
                    cargarTablaUsuarios();
                }
            } else {
                cargarTablaUsuarios();
            }
        } else {
            int respuesta = JOptionPane.showConfirmDialog(null,
                    "No es posible eliminar el usuario '" + cPadre + "/" + cUsuario + "' porque tiene servicios asociados. \nConsulte 'Mantenimiento de Servicios'.",
                    "Alerta", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            if (respuesta == JOptionPane.OK_OPTION || respuesta == JOptionPane.CLOSED_OPTION) {
                cargarTablaUsuarios();
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnMUGuardar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtCodigoUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));
        setMinimumSize(new java.awt.Dimension(510, 525));
        setPreferredSize(new java.awt.Dimension(510, 525));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 498));

        jLabel1.setBackground(new java.awt.Color(238, 238, 238));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Usuarios registrados:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel3.setBackground(new java.awt.Color(238, 238, 238));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Usuario:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnMUGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnMUGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMUGuardar.setForeground(new java.awt.Color(51, 51, 51));
        btnMUGuardar.setText("Guardar");
        btnMUGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMUGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMUGuardar.setDefaultCapable(false);
        btnMUGuardar.setFocusPainted(false);
        btnMUGuardar.setFocusable(false);
        btnMUGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMUGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUGuardarActionPerformed(evt);
            }
        });

        txtCodigoUsuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        tbUsuarios.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Eliminar usuario", "usr"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbUsuarios.setRowHeight(30);
        tbUsuarios.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tbUsuarios);
        if (tbUsuarios.getColumnModel().getColumnCount() > 0) {
            tbUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tbUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tbUsuarios.getColumnModel().getColumn(2).setMinWidth(0);
            tbUsuarios.getColumnModel().getColumn(2).setPreferredWidth(0);
            tbUsuarios.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        jLabel4.setBackground(new java.awt.Color(238, 238, 238));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/adduser.png"))); // NOI18N
        jLabel4.setText("Agregar usuario  ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txtCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMUGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMUGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMUGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUGuardarActionPerformed
        // TODO add your handling code here:
        String id = E_Usuario.generaIDregistro();
        String codigoUsuario = txtCodigoUsuario.getText().trim();
            if (!codigoUsuario.isEmpty()) {
                E_Usuario usuario = new E_Usuario();
                usuario.setIdRegistroUsuario(id);
                usuario.setCodigoUsuario(codigoUsuario);
                boolean agregado = AgregaUsuario(usuario);
                if (agregado) {
                    boolean actualizaArchivo = opciones.guardarUsuariosArchivo();
                    if (actualizaArchivo) {
                        ArchivoLogs.getInstance().grabaLogFileAdministrador("------ El usuario [" + usuario.toString() + "] fue agregado.", false);
                        JOptionPane.showMessageDialog(this, "El usuario ha sido agregada exitosamente", "Usuarios", JOptionPane.INFORMATION_MESSAGE);
                        opciones.realizarBKarchivo();
                        limpiarCampos();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario usuario '" + codigoUsuario + "' ya existe.", "Usuarios", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar el Usuario.", "Alerta", JOptionPane.ERROR_MESSAGE);
            }


    }//GEN-LAST:event_btnMUGuardarActionPerformed

    private boolean existeUsuarioEnServicios(String idRegistro) {
        for (E_Servicio s : GTXConfiguracionIG.ListaServicios) {
            if (s.getIdUsuario().equals(idRegistro)) {
                return true;
            }
        }
        return false;
    }

    private void limpiarCampos() {
        txtCodigoUsuario.setText("");
        cargarTablaUsuarios();
    }

    private boolean AgregaUsuario(E_Usuario nuevoUsuario) {
        for (E_Usuario u : GTXConfiguracionIG.ListaUsuarios) {
            if (u.getCodigoUsuario().equals(nuevoUsuario.getCodigoUsuario())) {
                return false;
            }
        }
        GTXConfiguracionIG.ListaUsuarios.add(nuevoUsuario);
        return true;
    }

    private boolean VentanaVisible() {
        return super.isVisible();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMUGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField txtCodigoUsuario;
    // End of variables declaration//GEN-END:variables
}
