package com.guatex.igconfiguraciones.formularios;

import com.guatex.igconfiguraciones.imagenes.RutasImagenes;
import com.guatex.igconfiguraciones.principal.GTXConfiguracionIG;
import com.guatex.igconfiguraciones.util.CifradoPassword;
import com.guatex.igconfiguraciones.util.Parametros;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;

/**
 *
 * @author ESTEFANIECM
 */
public class PanelAdministrador extends javax.swing.JFrame {

    private JButton selectedButton;

    /**
     * Creates new form PanelAdministrador
     */
    public PanelAdministrador() {
        initComponents();
        inicio();
        selectedButton = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpFondo = new javax.swing.JPanel();
        jpEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMImpresoras = new javax.swing.JButton();
        btnMUsuarios = new javax.swing.JButton();
        btnMServicio = new javax.swing.JButton();
        jpContenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnInivioVer = new javax.swing.JButton();
        lbIncorrecto = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnMParams = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agente de Impresión Guatex - 1.0.0");
        setIconImages(getIconImages());
        setResizable(false);

        jpFondo.setBackground(new java.awt.Color(255, 255, 255));
        jpFondo.setForeground(new java.awt.Color(51, 51, 51));
        jpFondo.setMinimumSize(new java.awt.Dimension(800, 600));
        jpFondo.setPreferredSize(new java.awt.Dimension(800, 600));

        jpEncabezado.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(237, 248, 253));
        jLabel1.setText("Administrador de servicio de impresión - GUATEX");

        javax.swing.GroupLayout jpEncabezadoLayout = new javax.swing.GroupLayout(jpEncabezado);
        jpEncabezado.setLayout(jpEncabezadoLayout);
        jpEncabezadoLayout.setHorizontalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEncabezadoLayout.setVerticalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnMImpresoras.setBackground(new java.awt.Color(255, 255, 255));
        btnMImpresoras.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMImpresoras.setForeground(new java.awt.Color(51, 51, 51));
        btnMImpresoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/print.png"))); // NOI18N
        btnMImpresoras.setBorderPainted(false);
        buttonGroup1.add(btnMImpresoras);
        btnMImpresoras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMImpresoras.setFocusPainted(false);
        btnMImpresoras.setFocusable(false);
        btnMImpresoras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMImpresoras.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMImpresoras.setLabel("  Mantenimiento de Impresoras");
        btnMImpresoras.setMaximumSize(new java.awt.Dimension(280, 100));
        btnMImpresoras.setMinimumSize(new java.awt.Dimension(280, 100));
        btnMImpresoras.setPreferredSize(new java.awt.Dimension(280, 100));
        btnMImpresoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMImpresorasActionPerformed(evt);
            }
        });

        btnMUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnMUsuarios.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        btnMUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/perfil.png"))); // NOI18N
        btnMUsuarios.setBorderPainted(false);
        buttonGroup1.add(btnMUsuarios);
        btnMUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMUsuarios.setFocusPainted(false);
        btnMUsuarios.setFocusable(false);
        btnMUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMUsuarios.setLabel("  Mantenimiento de Usuarios");
        btnMUsuarios.setMaximumSize(new java.awt.Dimension(280, 100));
        btnMUsuarios.setMinimumSize(new java.awt.Dimension(280, 100));
        btnMUsuarios.setPreferredSize(new java.awt.Dimension(280, 100));
        btnMUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUsuariosActionPerformed(evt);
            }
        });

        btnMServicio.setBackground(new java.awt.Color(255, 255, 255));
        btnMServicio.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMServicio.setForeground(new java.awt.Color(51, 51, 51));
        btnMServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/servicio.png"))); // NOI18N
        btnMServicio.setText("  Mantenimiento de Servicios");
        btnMServicio.setBorderPainted(false);
        buttonGroup1.add(btnMServicio);
        btnMServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMServicio.setDefaultCapable(false);
        btnMServicio.setFocusPainted(false);
        btnMServicio.setFocusable(false);
        btnMServicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMServicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMServicio.setMaximumSize(new java.awt.Dimension(280, 100));
        btnMServicio.setMinimumSize(new java.awt.Dimension(280, 100));
        btnMServicio.setPreferredSize(new java.awt.Dimension(280, 100));
        btnMServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMServicioActionPerformed(evt);
            }
        });

        jpContenedor.setBackground(new java.awt.Color(238, 238, 238));
        jpContenedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpContenedor.setMaximumSize(new java.awt.Dimension(520, 520));
        jpContenedor.setMinimumSize(new java.awt.Dimension(520, 520));
        jpContenedor.setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(510, 525));
        jPanel1.setMinimumSize(new java.awt.Dimension(510, 525));
        jPanel1.setPreferredSize(new java.awt.Dimension(510, 525));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/usuario.png"))); // NOI18N

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(51, 51, 51));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/clave (1).png"))); // NOI18N
        btnInicio.setText("   Ingresar");
        btnInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.setMaximumSize(new java.awt.Dimension(280, 100));
        btnInicio.setMinimumSize(new java.awt.Dimension(280, 100));
        btnInicio.setPreferredSize(new java.awt.Dimension(280, 100));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setToolTipText("");
        txtPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(238, 238, 238));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Contraseña:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnInivioVer.setBackground(new java.awt.Color(255, 255, 255));
        btnInivioVer.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnInivioVer.setForeground(new java.awt.Color(51, 51, 51));
        btnInivioVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/ver.png"))); // NOI18N
        btnInivioVer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInivioVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInivioVer.setDefaultCapable(false);
        btnInivioVer.setFocusPainted(false);
        btnInivioVer.setFocusable(false);
        btnInivioVer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInivioVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInivioVerActionPerformed(evt);
            }
        });

        lbIncorrecto.setBackground(new java.awt.Color(238, 238, 238));
        lbIncorrecto.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbIncorrecto.setForeground(new java.awt.Color(51, 51, 51));
        lbIncorrecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIncorrecto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbIncorrecto.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIncorrecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnInivioVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInivioVer, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbIncorrecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jpContenedor.add(jPanel1, java.awt.BorderLayout.CENTER);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/salir.png"))); // NOI18N
        btnSalir.setText(" Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalir.setBorderPainted(false);
        buttonGroup1.add(btnSalir);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusPainted(false);
        btnSalir.setFocusable(false);
        btnSalir.setMaximumSize(new java.awt.Dimension(280, 100));
        btnSalir.setMinimumSize(new java.awt.Dimension(280, 100));
        btnSalir.setPreferredSize(new java.awt.Dimension(280, 100));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnMParams.setBackground(new java.awt.Color(255, 255, 255));
        btnMParams.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMParams.setForeground(new java.awt.Color(51, 51, 51));
        btnMParams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guatex/igconfiguraciones/imagenes/configparams.png"))); // NOI18N
        btnMParams.setText("  Configurar parámetros");
        btnMParams.setBorderPainted(false);
        buttonGroup1.add(btnMParams);
        btnMParams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMParams.setDefaultCapable(false);
        btnMParams.setFocusPainted(false);
        btnMParams.setFocusable(false);
        btnMParams.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMParams.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMParams.setMaximumSize(new java.awt.Dimension(280, 100));
        btnMParams.setMinimumSize(new java.awt.Dimension(280, 100));
        btnMParams.setPreferredSize(new java.awt.Dimension(280, 100));
        btnMParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMParamsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMImpresoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jpEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(btnMImpresoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnMServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnMParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarbtnColores(JButton selected) {
        if (selectedButton != null) {
            // Restaurar el color del botón previamente seleccionado
            selectedButton.setBackground(null);
        }
        // Establecer el nuevo botón seleccionado
        selectedButton = selected;
        this.jpContenedor.setVisible(true);
        selectedButton.setBackground(new Color(238, 238, 238));
    }

    /*Botón Mantenimiento de Impresoras*/
    private void btnMImpresorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMImpresorasActionPerformed
        cambiarbtnColores(this.btnMImpresoras);
        jpContenedor.removeAll();
        jpContenedor.add(new P_Impresoras(), BorderLayout.CENTER);
        jpContenedor.repaint();
        jpContenedor.revalidate();
    }//GEN-LAST:event_btnMImpresorasActionPerformed

    /*Botón Mantenimiento de Usuarios*/
    private void btnMUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUsuariosActionPerformed
        cambiarbtnColores(this.btnMUsuarios);
        jpContenedor.removeAll();
        jpContenedor.add(new P_Usuarios(), BorderLayout.CENTER);
        jpContenedor.repaint();
        jpContenedor.revalidate();
    }//GEN-LAST:event_btnMUsuariosActionPerformed

    /*Botón Mantenimiento de Servicios*/
    private void btnMServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMServicioActionPerformed
        cambiarbtnColores(this.btnMServicio);
        jpContenedor.removeAll();
        jpContenedor.add(new P_Servicios(), BorderLayout.CENTER);
        jpContenedor.repaint();
        jpContenedor.revalidate();
    }//GEN-LAST:event_btnMServicioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        cambiarbtnColores(this.btnSalir);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    /*Botón Configuración de Parámetros*/
    private void btnMParamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMParamsActionPerformed
        cambiarbtnColores(this.btnMParams);
        jpContenedor.removeAll();
        jpContenedor.add(new P_Configuracion(), BorderLayout.CENTER);
        jpContenedor.repaint();
        jpContenedor.revalidate();
    }//GEN-LAST:event_btnMParamsActionPerformed

    private void inicio() {
        btnMParams.setEnabled(false);
        btnMServicio.setEnabled(false);
        btnMUsuarios.setEnabled(false);
        btnMImpresoras.setEnabled(false);
        char defaultEchoChar = txtPassword.getEchoChar();
        
        this.btnInivioVer.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                txtPassword.setEchoChar((char) 0);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                txtPassword.setEchoChar(defaultEchoChar);
            }
        });
        setIconImage(new RutasImagenes().getIcono());
        
        this.txtPassword.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnInicioActionPerformed(e);
            }
        });
    }

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        try {
            String passwordDesencriptada = "";
            String passwordIngreso = this.txtPassword.getText().trim().toUpperCase();
            String passwordDefinida = GTXConfiguracionIG.parametros.getProperty("password");
            if (passwordDefinida.isEmpty()) {
                passwordDefinida = Parametros.getPassword();
            }

            if (passwordIngreso.isEmpty()) {
                lbIncorrecto.setText("* Debe ingresar la contraseña *");
            } else {
                passwordDesencriptada = new CifradoPassword().decrypt(passwordDefinida);
                if (passwordIngreso.equals(passwordDesencriptada)) {
                    jpContenedor.removeAll();
                    jpContenedor.repaint();
                    jpContenedor.revalidate();
                    btnMParams.setEnabled(true);
                    btnMServicio.setEnabled(true);
                    btnMUsuarios.setEnabled(true);
                    btnMImpresoras.setEnabled(true);
                } else {
                    lbIncorrecto.setText("* La contraseña es incorrecta *");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnInivioVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInivioVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInivioVerActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed

    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked

    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        lbIncorrecto.setText("");
    }//GEN-LAST:event_txtPasswordMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInivioVer;
    private javax.swing.JButton btnMImpresoras;
    private javax.swing.JButton btnMParams;
    private javax.swing.JButton btnMServicio;
    private javax.swing.JButton btnMUsuarios;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JLabel lbIncorrecto;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
